### ISSUE TITLE
Flatten configuration examples with libStorage

### ISSUE THREAD

**Issue by clintonskitson** [emccode/polly#106]
It was decided recently for various reasons that when nesting libStorage config in other configurations, it is best to not nest the configuration. This means things like `polly.libstorage.` should now be translated to `libstorage.`.

We should be updating the testing packages and documentation to reflect the updated best practice for configuring libstorage related features under Polly.

**Comment by dvonthenen** [comment]
PR https://github.com/emccode/polly/pull/109 addressing this issue has been merged to master. Closing.
