### ISSUE TITLE
Test Polly with multiple backend stores

### ISSUE THREAD

**Issue by clintonskitson** [emccode/polly#23]
Polly needs to be tested across multiple backend stores.

**Comment by clintonskitson** [comment]
@dvonthenen Can you briefly document the backend store support?

**Comment by dvonthenen** [comment]
@clintonskitson will get to this shortly

**Comment by dvonthenen** [comment]
PR https://github.com/emccode/polly/pull/78 submitted for this issue.

**Comment by dvonthenen** [comment]
Merged supported backing stores
