### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by clintonskitson** [emccode/polly#28]
[ ] Install
[ ] Configuration
[ ] CLI
[ ] Architecture
[ ] Using
[ ] Supported store backends
[ ] Build process

**Comment by clintonskitson** [comment]
What does Polly do?

**Comment by dvonthenen** [comment]
Supported Store Backends: https://github.com/emccode/polly/pull/78 Merged
Build Process: https://github.com/emccode/polly/pull/79 Merged
