### ISSUE TITLE
Choose a default port for admin API

### ISSUE THREAD

**Issue by clintonskitson** [emccode/polly#38]

**Comment by dvonthenen** [comment]
Unless there are any objections, I am going to change the default port to 7978 as it is unclaimed according to iana.

http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=7978

**Comment by dvonthenen** [comment]
This PR https://github.com/emccode/polly/pull/60 should satisfy this issue. closing.
