### ISSUE TITLE
Panic traps sent to log

### ISSUE THREAD

**Issue by clintonskitson** [emccode/polly#68]
We need to be catching the panics and sending them to the log file. Right now we are missing a trap.

**Comment by dvonthenen** [comment]
@clintonskitson, I believe the logging for this already exists here: https://github.com/emccode/polly/blob/master/polly/cli/cli.go#L204

Can you please confirm?

**Comment by clintonskitson** [comment]
Not sure, see if you can trip a panic and make sure it is captured,
reported, and exited properly please.

**Comment by dvonthenen** [comment]
Will give it a try tomorrow morning.

**Comment by dvonthenen** [comment]
Closing issue as PR https://github.com/emccode/polly/pull/116 has been merged which addresses this issue.
