### ISSUE TITLE
Errors are being squashed

### ISSUE THREAD

**Issue by clintonskitson** [emccode/polly#88]
The errors are currently being squashed for any operations that occurs over the Polly API.

https://github.com/emccode/polly/issues/82

**Comment by dvonthenen** [comment]
This issue should be fixed now. If you are still seeing this, please reopen or file a new bug.

**Comment by dvonthenen** [comment]
Repo using latest Vagrant... looking into it

**Comment by dvonthenen** [comment]
This issue is on the rexray end of things. Will submit a PR there.

**Comment by dvonthenen** [comment]
PR https://github.com/emccode/rexray/pull/478 submitted for REX-Ray

**Comment by dvonthenen** [comment]
The PR in rexray has been merged and is tagged for the 0.4.1 release. Closing this tracking issue.
